export const kingdomList = [
  {
    name: "basic", cards: [
      { name: "冒険者", bane: false },
      { name: "役人", bane: false },
      { name: "地下貯蔵庫", bane: true },
      { name: "礼拝堂", bane: true },
      { name: "議事堂", bane: false },
      { name: "祝祭", bane: false },
      { name: "庭園", bane: false },
      { name: "研究所", bane: false },
      { name: "書庫", bane: false },
      { name: "市場", bane: false },
      { name: "民兵", bane: false },
      { name: "鉱山", bane: false },
      { name: "堀", bane: true },
      { name: "金貸し", bane: false },
      { name: "改築", bane: false },
      { name: "鍛冶屋", bane: false },
      { name: "玉座の間", bane: false },
      { name: "村", bane: true },
      { name: "魔女", bane: false },
      { name: "工房", bane: true },
      { name: "職人", bane: false },
      { name: "山賊", bane: false },
      { name: "前駆者", bane: true },
      { name: "商人", bane: true },
      { name: "密猟者", bane: false },
      { name: "衛兵", bane: false },
      { name: "家臣", bane: true }
    ]
  },
  {
    name: "intrigue", cards: [
      { name: "男爵", bane: false },
      { name: "橋", bane: false },
      { name: "共謀者", bane: false },
      { name: "銅細工師", bane: false },
      { name: "中庭", bane: true },
      { name: "公爵", bane: false },
      { name: "大広間", bane: true },
      { name: "ハーレム", bane: false },
      { name: "鉄工所", bane: false },
      { name: "仮面舞踏会", bane: true },
      { name: "鉱山の村", bane: false },
      { name: "寵臣", bane: false },
      { name: "貴族", bane: false },
      { name: "手先", bane: true },
      { name: "破壊工作員", bane: false },
      { name: "偵察員", bane: false },
      { name: "秘密の部屋", bane: true },
      { name: "貧民街", bane: true },
      { name: "執事", bane: true },
      { name: "詐欺師", bane: true },
      { name: "拷問人", bane: false },
      { name: "交易場", bane: false },
      { name: "貢物", bane: false },
      { name: "改良", bane: false },
      { name: "願いの井戸", bane: true }
    ]
  },
  {
    name: "seaside", cards: [
      { name: "原住民の村", bane: true },
      { name: "停泊所", bane: true },
      { name: "抑留", bane: true },
      { name: "真珠採り", bane: true },
      { name: "灯台", bane: true },
      { name: "漁村", bane: true },
      { name: "倉庫", bane: true },
      { name: "見張り", bane: true },
      { name: "密輸人", bane: true },
      { name: "大使", bane: true },
      { name: "引揚水夫", bane: false },
      { name: "宝の地図", bane: false },
      { name: "海の妖婆", bane: false },
      { name: "巾着切り", bane: false },
      { name: "隊商", bane: false },
      { name: "島", bane: false },
      { name: "航海士", bane: false },
      { name: "海賊船", bane: false },
      { name: "前哨地", bane: false },
      { name: "商船", bane: false },
      { name: "策士", bane: false },
      { name: "宝物庫", bane: false },
      { name: "探検家", bane: false },
      { name: "船着場", bane: false },
      { name: "バザー", bane: false },
      { name: "幽霊船", bane: false }
    ]
  },
  {
    name: "alchemy", cards: [
      { name: "薬草商", bane: true },
      { name: "薬師", bane: false },
      { name: "大学", bane: false },
      { name: "念視の泉", bane: false },
      { name: "錬金術師", bane: false },
      { name: "使い魔", bane: false },
      { name: "賢者の石", bane: false },
      { name: "ゴーレム", bane: false },
      { name: "弟子", bane: false },
      { name: "支配", bane: false },
      { name: "ブドウ園", bane: false },
      { name: "変成", bane: false }
    ]
  },
  {
    name: "prosperity", cards: [
      { name: "借金", bane: true },
      { name: "望楼", bane: true },
      { name: "交易路", bane: true },
      { name: "護符", bane: false },
      { name: "記念碑", bane: false },
      { name: "石切場", bane: false },
      { name: "司教", bane: false },
      { name: "労働者の村", bane: false },
      { name: "都市", bane: false },
      { name: "会計所", bane: false },
      { name: "香具師", bane: false },
      { name: "保管庫", bane: false },
      { name: "禁制品", bane: false },
      { name: "造幣所", bane: false },
      { name: "玉璽", bane: false },
      { name: "大衆", bane: false },
      { name: "投機", bane: false },
      { name: "隠し財産", bane: false },
      { name: "大市場", bane: false },
      { name: "ならず者", bane: false },
      { name: "拡張", bane: false },
      { name: "鍛造", bane: false },
      { name: "宮廷", bane: false },
      { name: "銀行", bane: false },
      { name: "行商人", bane: false }
    ]
  },
  {
    name: "cornucopia", cards: [
      { name: "村落", bane: true },
      { name: "占い師", bane: true },
      { name: "移動動物園", bane: true },
      { name: "馬上槍試合", bane: false },
      { name: "再建", bane: false },
      { name: "農村", bane: false },
      { name: "馬商人", bane: false },
      { name: "魔女娘", bane: false },
      { name: "狩猟団", bane: false },
      { name: "収穫", bane: false },
      { name: "豊穣の角笛", bane: false },
      { name: "道化師", bane: false },
      { name: "品評会", bane: false }
    ]
  },
  {
    name: "hinterlands", cards: [
      { name: "愚者の黄金", bane: true },
      { name: "岐路", bane: true },
      { name: "公爵夫人", bane: true },
      { name: "坑道", bane: true },
      { name: "神託", bane: true },
      { name: "開発", bane: true },
      { name: "画策", bane: true },
      { name: "オアシス", bane: true },
      { name: "義賊", bane: false },
      { name: "遊牧民の野営地", bane: false },
      { name: "よろずや", bane: false },
      { name: "交易人", bane: false },
      { name: "シルクロード", bane: false },
      { name: "香辛料商人", bane: false },
      { name: "不正利得", bane: false },
      { name: "官吏", bane: false },
      { name: "大使館", bane: false },
      { name: "宿屋", bane: false },
      { name: "地図職人", bane: false },
      { name: "埋蔵金", bane: false },
      { name: "街道", bane: false },
      { name: "辺境伯", bane: false },
      { name: "厩舎", bane: false },
      { name: "値切り屋", bane: false },
      { name: "国境の村", bane: false },
      { name: "農地", bane: false }
    ]
  },
  {
    name: "dark_ages", cards: [
      { name: "救貧院", bane: false },
      { name: "従者", bane: true },
      { name: "物乞い", bane: true },
      { name: "浮浪者", bane: true },
      { name: "青空市場", bane: true },
      { name: "浮浪児", bane: true },
      { name: "物置", bane: true },
      { name: "隠遁者", bane: true },
      { name: "賢者", bane: true },
      { name: "採集者", bane: true },
      { name: "城塞", bane: false },
      { name: "吟遊詩人", bane: false },
      { name: "死の荷車", bane: false },
      { name: "襲撃者", bane: false },
      { name: "封土", bane: false },
      { name: "武器庫", bane: false },
      { name: "金物商", bane: false },
      { name: "行進", bane: false },
      { name: "ネズミ", bane: false },
      { name: "ゴミあさり", bane: false },
      { name: "墓暴き", bane: false },
      { name: "屑屋", bane: false },
      { name: "山賊の宿営地", bane: false },
      { name: "狂信者", bane: false },
      { name: "略奪", bane: false },
      { name: "地下墓所", bane: false },
      { name: "騎士", bane: false },
      { name: "建て直し", bane: false },
      { name: "はみだし者", bane: false },
      { name: "盗賊", bane: false },
      { name: "偽造通貨", bane: false },
      { name: "秘術師", bane: false },
      { name: "伯爵", bane: false },
      { name: "狩場", bane: false },
      { name: "祭壇", bane: false }
    ]
  },
  {
    name: "guild", cards: [
      { name: "蝋燭職人", bane: true },
      { name: "医者", bane: true },
      { name: "名品", bane: true },
      { name: "広場", bane: false },
      { name: "助言者", bane: false },
      { name: "伝令官", bane: false },
      { name: "商人ギルド", bane: false },
      { name: "パン屋", bane: false },
      { name: "肉屋", bane: false },
      { name: "熟練工", bane: false },
      { name: "予言者", bane: false },
      { name: "石工", bane: true },
      { name: "収税吏", bane: false }
    ]
  },
  {
    name: "adventures", cards: [
      { name: "法貨", bane: true },
      { name: "農民", bane: true },
      { name: "騎士見習い", bane: true },
      { name: "鼠取り", bane: true },
      { name: "倒壊", bane: true },
      { name: "道具", bane: true },
      { name: "魔除け", bane: true },
      { name: "隊商の護衛", bane: true },
      { name: "地下牢", bane: true },
      { name: "案内人", bane: true },
      { name: "港町", bane: false },
      { name: "山守", bane: false },
      { name: "変容", bane: false },
      { name: "守銭奴", bane: false },
      { name: "複製", bane: false },
      { name: "カササギ", bane: false },
      { name: "使者", bane: false },
      { name: "語り部", bane: false },
      { name: "掘出物", bane: false },
      { name: "ワイン商", bane: false },
      { name: "橋の下のトロル", bane: false },
      { name: "沼の妖婆", bane: false },
      { name: "呪いの森", bane: false },
      { name: "工匠", bane: false },
      { name: "遠隔地", bane: false },
      { name: "御料車", bane: false },
      { name: "失われし都市", bane: false },
      { name: "巨人", bane: false },
      { name: "遺物", bane: false },
      { name: "雇人", bane: false }
    ]
  },
  {
    name: "empires", cards: [
      { name: "大君主", bane: false },
      { name: "技術者", bane: false },
      { name: "王室の鍛冶屋", bane: false },
      { name: "市街", bane: false },
      { name: "パトリキ/エンポリウム", bane: true },
      { name: "陣地/鹵獲品", bane: true },
      { name: "開拓者/騒がしい村", bane: true },
      { name: "投石機/石", bane: true },
      { name: "女魔術師", bane: true },
      { name: "剣闘士/大金", bane: true },
      { name: "城", bane: true },
      { name: "戦車競走", bane: true },
      { name: "農家の市場", bane: true },
      { name: "ヴィラ", bane: false },
      { name: "生贄", bane: false },
      { name: "神殿", bane: false },
      { name: "ワイルドハント", bane: false },
      { name: "冠", bane: false },
      { name: "公共広場", bane: false },
      { name: "軍団兵", bane: false },
      { name: "元手", bane: false },
      { name: "御守り", bane: false },
      { name: "資料庫", bane: false },
      { name: "庭師", bane: false }
    ],
  }
];

export const eventList = [
  { name: "施し" },
  { name: "舞踏会" },
  { name: "焚火" },
  { name: "借入" },
  { name: "探検" },
  { name: "渡し船" },
  { name: "相続" },
  { name: "失われた技術" },
  { name: "使節団" },
  { name: "誘導" },
  { name: "巡礼" },
  { name: "立案" },
  { name: "探索" },
  { name: "奇襲" },
  { name: "保存" },
  { name: "偵察隊" },
  { name: "海路" },
  { name: "交易" },
  { name: "鍛錬" },
  { name: "移動遊園地" },
  { name: "昇進" },
  { name: "併合" },
  { name: "宴会" },
  { name: "征服" },
  { name: "掘進" },
  { name: "制圧" },
  { name: "寄付" },
  { name: "儀式" },
  { name: "大地への塩まき" },
  { name: "徴税" },
  { name: "凱旋" },
  { name: "結婚式" },
  { name: "意外な授かり物" }
];

export const landmarkList = [
  { name: "水道橋" },
  { name: "闘技場" },
  { name: "山賊の砦" },
  { name: "公会堂" },
  { name: "浴場" },
  { name: "戦場" },
  { name: "列柱" },
  { name: "汚された神殿" },
  { name: "噴水" },
  { name: "砦" },
  { name: "迷宮" },
  { name: "峠" },
  { name: "博物館" },
  { name: "オベリスク" },
  { name: "果樹園" },
  { name: "宮殿" },
  { name: "墓標" },
  { name: "塔" },
  { name: "凱旋門" },
  { name: "壁" },
  { name: "狼の巣" }
];
